pretrained_model_path: "/path/to/model"
output_dir: "/path/to/output"

train_data:
  csv_path: "/path/to/csv"
  n_sample_frames: 1
  width: 512
  height: 512
  sample_frame_rate: 4  # frame stride

validation_data:
  prompts:
    - "Nice glass window"
    - "Red Cylinder, Blue target point"
    - "Brown ferrule and green handle, Red Cylinder"
    - "Green drawer"
    - "Black metal safety door"
    - "Black metal safety door, Door close, (Close)"
    - "Grey faucet with red handle"
    - "White soccer net side"
  video_length: 16
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 7.5
  use_inv_latent: False
  num_inv_steps: 50
  dataset_set: "val"

learning_rate: 1e-5
train_batch_size: 8
num_workers: 16
max_train_steps: 10000
checkpointing_steps: 2500
validation_steps: 500
trainable_modules:
  - "skeleton_adapter"
  # - "attn1.to_q"
  # - "attn2.to_q"
  # - "attn_temp"
  # - "conv_temporal"

use_skeleton_train: True
skeleton_path: "/path/to/pose.mp4"

seed: 33
mixed_precision: "fp16"
use_8bit_adam: False
gradient_checkpointing: False
gradient_accumulation_steps: 2
enable_xformers_memory_efficient_attention: True
