pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "output"


validation_data:
  prompts:
    - "Red Cylinder, Red target point"
    - "Red Cylinder, Blue target point"
    - "Brown ferrule and green handle, Red Cylinder"
    - "Brown ferrule and green handle, Red Cylinder, Ring outside the column, (Outside)"
    - "Black metal safety door"
    - "Black metal safety door, Door close, (Close)"
  video_length: 24
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 7.5
  use_inv_latent: False
  num_inv_steps: 50
  dataset_set: "val"


train_batch_size: 1
validation_steps: 100

# python zero_to_fp32.py /home/ao/workspace/FollowYourPose/output/checkpoint-10000 /home/ao/workspace/FollowYourPose/output/checkpoint-10000/pytorch_model.bin --tag=pytorch_model
# resume_from_checkpoint: /home/ao/workspace/FollowYourPose/output/checkpoint-10000
# skeleton_path: './pose_example/metaworld_ButtonPress_20240826_205555_pose.mp4'
skeleton_path: '/home/ao/workspace/diffusers/video_data_human/metaworld_Instruct_20240826_163500_pose.mp4'

seed: 33
mixed_precision: 'fp16'
gradient_checkpointing: False
enable_xformers_memory_efficient_attention: True
