pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "output"


validation_data:
  prompts:
    - "Nice glass window"
    - "Red Cylinder, Blue target point"
    - "Brown ferrule and green handle, Red Cylinder"
    - "Green drawer"
    - "Black metal safety door"
    - "Black metal safety door, Door close, (Close)"
    - "Grey faucet with red handle"
    - "White soccer net side"
  video_length: 24
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 7.5
  use_inv_latent: False
  num_inv_steps: 50
  dataset_set: "val"


train_batch_size: 1
validation_steps: 100

skeleton_path: '/path/to/pose.mp4'

seed: 33
mixed_precision: 'fp16'
gradient_checkpointing: False
enable_xformers_memory_efficient_attention: True
