pretrained_model_path: "/home/ao/workspace/FollowYourPose/diffusers/metaworld-1009-0214"
# pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "output-1009-0214"

train_data:
  csv_path: "/home/ao/workspace/fs/diffusers/meta_caption_p_A_f.csv"
  n_sample_frames: 1
  width: 512
  height: 512
  sample_frame_rate: 4  # frame stride

validation_data:
  prompts:
    - "Red Cylinder, Red target point"
    - "Red Cylinder, Blue target point"
    - "Brown ferrule and green handle, Red Cylinder"
    - "Brown ferrule and green handle, Red Cylinder, Ring outside the column, (Outside)"
    - "Black metal safety door"
    - "Black metal safety door, Door close, (Close)"
  video_length: 16
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 6.5
  use_inv_latent: False
  num_inv_steps: 50
  dataset_set: "val"

learning_rate: 1e-5
train_batch_size: 8
num_workers: 16
max_train_steps: 20000
checkpointing_steps: 10000
validation_steps: 500
trainable_modules:
  - "skeleton_adapter"
  # - "attn1.to_q"
  # - "attn2.to_q"
  # - "attn_temp"
  # - "conv_temporal"

use_skeleton_train: True
skeleton_path: '/home/ao/workspace/FollowYourPose/pose_example/pose.mp4'

seed: 33
mixed_precision: 'fp16'
use_8bit_adam: False
gradient_checkpointing: False
gradient_accumulation_steps: 2
enable_xformers_memory_efficient_attention: True
