pretrained_model_path: "/home/ao/workspace/FollowYourPose/diffusers/metaworld-1002-1800"
output_dir: "output-1008-0225"

train_data:
  csv_path: "/home/ao/workspace/fs/diffusers/meta_caption_pr_A_f_2.csv"
  n_sample_frames: 12
  width: 512
  height: 512
  sample_frame_rate: 4  # frame stride

validation_data:
  prompts:
    - "Red Cylinder, Red target point"
    - "Red Cylinder, Blue target point"
    - "Brown ferrule and green handle, Red Cylinder"
    - "Brown ferrule and green handle, Red Cylinder, Ring outside the column, (Outside)"
    - "Black metal safety door"
    - "Black metal safety door, Door close, (Close)"
  video_length: 16
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 6.5
  use_inv_latent: False
  num_inv_steps: 50
  dataset_set: "val"

learning_rate: 1e-5
train_batch_size: 2
num_workers: 16
max_train_steps: 30000
checkpointing_steps: 10000
validation_steps: 500
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"
  - "conv_temporal"

use_skeleton_train: True
skeleton_path: '/home/ao/workspace/fs/diffusers/video_data/metaworld_assembly-v2-goal-observable_20240926_004915_pose.mp4'

seed: 33
mixed_precision: 'fp16'
use_8bit_adam: False
gradient_checkpointing: True
gradient_accumulation_steps: 2
enable_xformers_memory_efficient_attention: True
