pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "output"

train_data:
  csv_path: "/home/sora/workspace/meta_caption_instruct.csv"
  n_sample_frames: 12
  width: 512
  height: 512
  sample_frame_rate: 8  # frame stride

validation_data:
  prompts:
    - "This is a computer-generated simulated environment featuring a robotic arm with a gripper attached to its end, a table, and several objects in the environment. The robotic arm is red, and the two fingers of the gripper are white and blue respectively. The table is made of brown wood, with gray vertical barriers added to its edges. There are shadows for all objects in the environment. The simulated environment looks very realistic and adheres to physical laws. There is a red cylinder on the table."
  video_length: 24
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: False
  num_inv_steps: 50
  dataset_set: "val"

learning_rate: 3e-5
train_batch_size: 2
num_workers: 4
max_train_steps: 50000
checkpointing_steps: 5000
validation_steps: 5000
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"
  - "conv_temporal"

use_skeleton_train: True
skeleton_path: './pose_example/metaworld_ButtonPress_20240826_205555_pose.mp4'

seed: 33
mixed_precision: 'bf16'
use_8bit_adam: False
gradient_checkpointing: True
gradient_accumulation_steps: 1
enable_xformers_memory_efficient_attention: True
